---
- name: Install and update packages
  hosts: dev 
  become: true
  vars: 
    package: "@RPM Development Tools"

  tasks:
    - name: Install the latest version of vim
      ansible.builtin.dnf:
        name: vim
        state: latest 
 
    - name: Install RPM Development Tools
      ansible.builtin.dnf:
        name: "{{ package }}"
        state: latest

    - name: Upgrade all packages to the latest versions
      ansible.builtin.dnf:
        name: "*"
        state: latest
 
