---

- name: Adding user across all hosts
  hosts: all
  become: true
  vars_files:
    - /home/automation/ansible1/secret.yml


  
  tasks:
      
    - name: Add a new user with a bash shell 
      ansible.builtin.user:
        name: jdoe
        comment: "Jane Doe"
        shell: /bin/bash
        groups: goldenstate
        password: "{{ password | password_hash('sha512') }}"

    - name: Display the secret_message variable
      ansible.builtin.debug:
        msg: "{{secret_message}}"
